### ISSUE TITLE
Tasks tab is not clickable when PWA window is below certain size

### ISSUE THREAD

**Issue by chippy** [flowmodor/flowmodor#35] opened 2024-10-22 14:36 UTC
If using Flomodor as a standard browser page, when the page is shrunk below a certain size, the sidebar disappears, presumably this is a breakpoint for a responsive layout. The app continues to work correctly. 

However, if I open the page in Chroma as a PWA, if I shrink the window to the size where the sidebar disappears, the heading of the Tasks tab becomes un-clickable (or at least, nothing happens when it is clicked, we stay on the timer view instead of switching to Tasks). When I make the window larger so that the sidebar appears, the Tasks tab starts working again.

This is using Chrome on MacOS,

**Comment by m4xshen** [comment] 2024-10-22 14:47
Hi @chippy thanks for the bug report. Could you please provide a screen record of the current behavior? I can't reproduce the issue.

**Comment by chippy** [comment] 2024-10-22 15:29
Hi @m4xshen. Screen recording attached. While taking this, I realised the issue is not quite what I thought. You can click the Tasks tab, but it is inconsistent about when the mouse pointer turns into the hand icon, indicating that it can be clicked, and sometimes it only works if you're clicking in specific places. For example, it's hard to see in the video because you can't tell when I'm clicking, but, at 0:39 in the video, I'm clicking directly on the 'Tasks' text, but nothing is happening. But when I move the pointer and click about 1cm to the right of the 'Tasks' text, it switches tab. However earlier in the video, clicking directly on the text works, so it's not always the case. I can see why this might be tricky to reproduce.

https://github.com/user-attachments/assets/f51ef9d1-4fee-4f5c-b78a-bba8eda7776e

**Comment by m4xshen** [comment] 2024-10-22 23:47
It should be fixed now. If you still encounter any issue just tell me!

**Closed by m4xshen** 2024-10-22 23:47 UTC
Labels: bug

**Comment by chippy** [comment] 2024-10-23 09:19
Looks good! Thanks for the fast turnaround.
