### ISSUE TITLE
"Select a Task" is missing in the web app

### ISSUE THREAD

**Issue by 1chooo** [flowmodor/flowmodor#43] opened 2024-11-25 12:32 UTC
In the mobile app we could find the drop-down menu to choose the tasks; however, we did not find the drop-down menu to choose the tasks. We have to go to "tasks" tab to choose the task and go back to the timer to start. It may lead to one-more-step to start the timer. Therefore, maybe we need to fix this bug or add the new feature to support this

### Screenshots

https://github.com/user-attachments/assets/06ecb931-3bbb-4d47-a1e4-adb6cdc4d38b

<img width="400" alt="Screenshot 2024-11-25 at 8 27 37 PM" src="https://github.com/user-attachments/assets/767883ff-1b97-4b42-9fe4-08d3b1498336">

### Expected

We may find the "select a task" drop-down menu when we use the browser.

**Comment by m4xshen** [comment] 2024-11-25 15:53
Thanks for reminding me this. Originally there's a task selector but it was removed in 5d790af2496fa336e653615b5354bd30fdc6def2 because the layout of home page changed to side-by-side for experiment. Now it is changed back to 2 tabs layout and the task selector should be added back.

**Comment by arjun6757** [comment] 2024-12-25 21:53
can i work in this @m4xshen ?

**Comment by m4xshen** [comment] 2024-12-26 02:25
@arjun6757 Sure! Please use `@nextui-org/select` to do it.

**Comment by arjun6757** [comment] 2024-12-26 15:19
is this okay @m4xshen ?
on length 0 =>
![onlengthzero](https://github.com/user-attachments/assets/1d55bb25-8b4b-4223-8ea5-25b75e7f0b14)
on child => 
![onChild](https://github.com/user-attachments/assets/836ee64d-7b6c-4cdb-921a-7c65b8982624)

**Comment by m4xshen** [comment] 2024-12-26 16:03
The trigger should look like the mobile version:

<img src="https://github.com/user-attachments/assets/c77d908d-c100-4fa5-9810-1e0bb4ca9614" width="100" />

but works just like normal nextui select.

**Comment by arjun6757** [comment] 2024-12-27 14:05
something like this ? [screen-capture (16).webm](https://github.com/user-attachments/assets/d34b5da9-841f-4e5c-ac3f-c7ee8db23293)

**Comment by m4xshen** [comment] 2024-12-27 15:52
Yeah, but when there's a task selected, it should show the task name instead of "Select a task".

**Comment by arjun6757** [comment] 2024-12-27 16:10
@m4xshen that was just a demo....i will send another video after completion

**Comment by arjun6757** [comment] 2024-12-27 19:26
[screen-capture (17).webm](https://github.com/user-attachments/assets/5e4f92f9-c51c-4e66-aa99-c01adcf5f4c1) let me know if anything is missing, also im using useTasks() for tasks so this covers all the tasks right ?

**Comment by m4xshen** [comment] 2024-12-28 01:04
> im using useTasks() for tasks

Yes, this is the correct way.

The result looks good, you can open a PR!

**Comment by 1chooo** [comment] 2024-12-28 08:13
@m4xshen @arjun6757 

Looks good to me! I would like to suggest keeping the right arrow visible when selecting a task. This way, users will know they can still change tasks. What do you think?

**Comment by arjun6757** [comment] 2024-12-28 08:20
@1chooo oh so you mean the task name with the icon ?

**Comment by arjun6757** [comment] 2024-12-28 10:26
@1chooo how is it 
on overflowing ![image](https://github.com/user-attachments/assets/6f9931b1-bbe0-4062-b9ae-665f64093d6b)
on normal 
![image](https://github.com/user-attachments/assets/e9bbaa18-622f-4c31-ad32-70f2e06c8143)

**Comment by arjun6757** [comment] 2024-12-28 10:30
@m4xshen @1chooo when im hovering over an element and closing without doing anything and reopening again it is showing the one i hovered but in the default color which property handles that i can't find in docs 
talking about this one -->
![image](https://github.com/user-attachments/assets/0ee30011-ce01-40e2-b30c-44d2c8d918af)
the classname i used in select item => base: 'data-[selected=true]:!bg-secondary data-[hover=true]:!bg-secondary data-[focus=true]:!bg-secondary'

**Comment by m4xshen** [comment] 2024-12-28 11:27
>  over an element and closing without doing anything and reopening again

Could you record it as video? I can't reproduce the issue by following the instruction.

**Comment by arjun6757** [comment] 2024-12-28 11:38
@m4xshen here you go
[screen-capture (18).webm](https://github.com/user-attachments/assets/e61c1d64-ceaa-4d88-a581-3072bc14c40a)
you can clearly see that if im hovering over it then it is changing the color and if it is selected then all good but only in this scneario where im hovering over an item and not selecting it and just completely closing the *select* it retains that info and shows it in default color

**Comment by m4xshen** [comment] 2024-12-28 12:07
Hmm, I had this issue before, but I couldn’t find a way to resolve it. Maybe we can just leave it as it is for now.

**Comment by arjun6757** [comment] 2024-12-28 12:13
@m4xshen okay im creating a PR then

**Closed** 2024-12-29 13:40 UTC
Labels: enhancement
